/* *****************************************
 * CSCI205 - Software Engineering and Design
 * Spring 2016
 *
 * Name: NAMES of team members
 * Date: Apr 19, 2016
 * Time: 7:54:12 PM
 *
 * Project: csci205FinalProject
 * Package: Monopoly.view
 * File: MonopolyView
 * Description:
 *
 * ****************************************
 */
package Monopoly.view;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author emo006
 */
public class MonopolyView extends javax.swing.JFrame {

    /**
     * Creates new form EditedMonopolyView
     */
    public MonopolyView() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Monopoly!");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        getMessagesPanel().setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlayDialog = new javax.swing.JDialog();
        inputPanel = new javax.swing.JPanel();
        javax.swing.JLabel lblP1 = new javax.swing.JLabel();
        javax.swing.JLabel lblP2 = new javax.swing.JLabel();
        javax.swing.JLabel lblP3 = new javax.swing.JLabel();
        javax.swing.JLabel lblP4 = new javax.swing.JLabel();
        txtP1 = new javax.swing.JTextField();
        txtP2 = new javax.swing.JTextField();
        txtP3 = new javax.swing.JTextField();
        txtP4 = new javax.swing.JTextField();
        javax.swing.JLabel lblGreeting1 = new javax.swing.JLabel();
        lblGreeting2 = new javax.swing.JLabel();
        playBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        TakeTurnPanel = new javax.swing.JPanel();
        currTurnLabel = new javax.swing.JLabel();
        currPlayerNameLabel = new javax.swing.JLabel();
        checkForMonopBttn = new javax.swing.JButton();
        rollDiceButton = new javax.swing.JButton();
        EndGameButton = new javax.swing.JButton();
        communityPotTitleLabel = new javax.swing.JLabel();
        communityPotAmtLabel = new javax.swing.JLabel();
        p1StatsPanel = new javax.swing.JPanel();
        javax.swing.JLabel p1JailStatusLbl = new javax.swing.JLabel();
        p1StatsTitleLbl = new javax.swing.JLabel();
        javax.swing.JLabel p1BankAccountLbl = new javax.swing.JLabel();
        p1BalanceLbl = new javax.swing.JLabel();
        javax.swing.JLabel p1PropertiesLbl = new javax.swing.JLabel();
        p1IsInJailLbl = new javax.swing.JLabel();
        javax.swing.JLabel p1CurrentSpaceLbl = new javax.swing.JLabel();
        p1LocationLbl = new javax.swing.JLabel();
        P1ScrollPane = new javax.swing.JScrollPane();
        P1PropOwnedArea = new javax.swing.JTextArea();
        p2StatsPanel = new javax.swing.JPanel();
        javax.swing.JLabel p2JailStatusLbl = new javax.swing.JLabel();
        p2StatsTitleLbl = new javax.swing.JLabel();
        javax.swing.JLabel p2BankAccountLbl = new javax.swing.JLabel();
        p2BalanceLbl = new javax.swing.JLabel();
        javax.swing.JLabel p2PropertiesLbl = new javax.swing.JLabel();
        p2IsInJailLbl = new javax.swing.JLabel();
        javax.swing.JLabel p2CurrentSpaceLbl = new javax.swing.JLabel();
        p2LocationLbl = new javax.swing.JLabel();
        P2ScrollPane = new javax.swing.JScrollPane();
        P2PropOwnedArea = new javax.swing.JTextArea();
        p3StatsPanel = new javax.swing.JPanel();
        javax.swing.JLabel p3JailStatusLbl = new javax.swing.JLabel();
        p3StatsTitleLbl = new javax.swing.JLabel();
        javax.swing.JLabel p3BankAccountLbl = new javax.swing.JLabel();
        p3BalanceLbl = new javax.swing.JLabel();
        javax.swing.JLabel p3PropertiesLbl = new javax.swing.JLabel();
        p3IsInJailLbl = new javax.swing.JLabel();
        javax.swing.JLabel p3CurrentSpaceLbl = new javax.swing.JLabel();
        p3LocationLbl = new javax.swing.JLabel();
        P3ScrollPane = new javax.swing.JScrollPane();
        P3PropOwnedArea = new javax.swing.JTextArea();
        p4StatsPanel = new javax.swing.JPanel();
        javax.swing.JLabel p4JailStatusLbl = new javax.swing.JLabel();
        p4StatsTitleLbl = new javax.swing.JLabel();
        javax.swing.JLabel p4BankAccountLbl = new javax.swing.JLabel();
        p4BalanceLbl = new javax.swing.JLabel();
        javax.swing.JLabel p4PropertiesLbl = new javax.swing.JLabel();
        p4IsInJailLbl = new javax.swing.JLabel();
        javax.swing.JLabel p4CurrentSpaceLbl = new javax.swing.JLabel();
        p4LocationLbl = new javax.swing.JLabel();
        P4ScrollPane = new javax.swing.JScrollPane();
        P4PropOwnedArea = new javax.swing.JTextArea();
        boardImg = new javax.swing.JLabel();
        messagesPanel = new javax.swing.JPanel();
        dicePanel = new javax.swing.JPanel();
        makeMoveButton = new javax.swing.JButton();
        dice1Lbl = new javax.swing.JLabel();
        dice2Lbl = new javax.swing.JLabel();
        javax.swing.JLabel messagesLbl1 = new javax.swing.JLabel();
        propDisplayPanel = new javax.swing.JPanel();
        propPanel = new javax.swing.JPanel();
        propPriceTitleLabel = new javax.swing.JLabel();
        propPriceLabel = new javax.swing.JLabel();
        propPurchaseYesButton = new javax.swing.JButton();
        propPurchaseNoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel messagesLbl2 = new javax.swing.JLabel();
        propNameLabel = new javax.swing.JLabel();
        propTitleLabel = new javax.swing.JLabel();
        genPopupPanel = new javax.swing.JPanel();
        genPopupLabel = new javax.swing.JLabel();
        genPopupEndTurnButton = new javax.swing.JButton();
        javax.swing.JLabel messagesLbl4 = new javax.swing.JLabel();
        propPurchaseOutcomePanel = new javax.swing.JPanel();
        propPurchaseOutcomeLabel = new javax.swing.JLabel();
        propPurchaseEndTurnButton = new javax.swing.JButton();
        javax.swing.JLabel messagesLbl5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        monopPanel = new javax.swing.JPanel();
        monopLabel = new javax.swing.JLabel();
        monopYesBttn = new javax.swing.JButton();
        monopNoBttn = new javax.swing.JButton();
        javax.swing.JLabel messagesLbl8 = new javax.swing.JLabel();
        yesMonopPanel = new javax.swing.JPanel();
        yesMonopPane = new javax.swing.JScrollPane();
        yesMonopArea = new javax.swing.JTextArea();
        yesMonopLbl1 = new javax.swing.JLabel();
        yesMonopLbl2 = new javax.swing.JLabel();
        yesMonopField = new javax.swing.JTextField();
        buildBttn = new javax.swing.JButton();
        javax.swing.JLabel messagesLbl7 = new javax.swing.JLabel();
        noMonopolyPanel = new javax.swing.JPanel();
        noMonopOkBttn = new javax.swing.JButton();
        noMonopLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        payRentPropertyPanel = new javax.swing.JPanel();
        payRentOutcomeLabel = new javax.swing.JLabel();
        payRentEndTurnButton = new javax.swing.JButton();
        payRentLocationLabel = new javax.swing.JLabel();
        javax.swing.JLabel messagesLbl6 = new javax.swing.JLabel();
        EndGamePanel = new javax.swing.JPanel();
        endOfGameStatsLabel = new javax.swing.JLabel();
        firstPlaceTitleLabel = new javax.swing.JLabel();
        firstPlaceLabel = new javax.swing.JLabel();
        quitGameButton = new javax.swing.JButton();
        javax.swing.JLabel messageLbl3 = new javax.swing.JLabel();

        PlayDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        PlayDialog.setTitle("Enter Player Names");
        PlayDialog.setAlwaysOnTop(true);
        PlayDialog.setMinimumSize(new java.awt.Dimension(325, 289));
        PlayDialog.setName("InputPlayers"); // NOI18N
        PlayDialog.setResizable(false);
        PlayDialog.setSize(new java.awt.Dimension(200, 200));

        lblP1.setText("Player1 : ");

        lblP2.setText("Player 2 : ");

        lblP3.setText("Player 3 : ");

        lblP4.setText("Player 4 :");

        txtP1.setText("Player 1");

        txtP2.setText("Player 2");
        txtP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtP2ActionPerformed(evt);
            }
        });

        txtP3.setText("Player 3");

        txtP4.setText("Player 4");

        lblGreeting1.setText("Welcome to Monopoly!");

        lblGreeting2.setText("      Please enter the names of the players below.");

        javax.swing.GroupLayout inputPanelLayout = new javax.swing.GroupLayout(inputPanel);
        inputPanel.setLayout(inputPanelLayout);
        inputPanelLayout.setHorizontalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(inputPanelLayout.createSequentialGroup()
                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(inputPanelLayout.createSequentialGroup()
                                        .addComponent(lblP3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtP3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(inputPanelLayout.createSequentialGroup()
                                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(inputPanelLayout.createSequentialGroup()
                                                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblP2)
                                                    .addComponent(lblP1))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, inputPanelLayout.createSequentialGroup()
                                                .addComponent(lblP4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtP2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtP4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(inputPanelLayout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addComponent(lblGreeting1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblGreeting2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        inputPanelLayout.setVerticalGroup(
            inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblGreeting1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGreeting2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblP1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblP2))
                .addGap(8, 8, 8)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblP3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(inputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblP4))
                .addGap(6, 6, 6))
        );

        playBtn.setText("Play");
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PlayDialogLayout = new javax.swing.GroupLayout(PlayDialog.getContentPane());
        PlayDialog.getContentPane().setLayout(PlayDialogLayout);
        PlayDialogLayout.setHorizontalGroup(
            PlayDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayDialogLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
            .addComponent(inputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );
        PlayDialogLayout.setVerticalGroup(
            PlayDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayDialogLayout.createSequentialGroup()
                .addComponent(inputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(PlayDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitBtn)
                    .addComponent(playBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1030, 994));
        setMinimumSize(new java.awt.Dimension(1030, 994));
        setResizable(false);

        TakeTurnPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        currTurnLabel.setText("Player's Turn:");

        currPlayerNameLabel.setText("Player");

        checkForMonopBttn.setText("Build Houses");

        rollDiceButton.setText("Roll Dice!");

        EndGameButton.setText("End Game");

        communityPotTitleLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        communityPotTitleLabel.setText("Community Pot:     $");

        communityPotAmtLabel.setText("0");

        javax.swing.GroupLayout TakeTurnPanelLayout = new javax.swing.GroupLayout(TakeTurnPanel);
        TakeTurnPanel.setLayout(TakeTurnPanelLayout);
        TakeTurnPanelLayout.setHorizontalGroup(
            TakeTurnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TakeTurnPanelLayout.createSequentialGroup()
                .addGroup(TakeTurnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TakeTurnPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(currTurnLabel)
                        .addGap(38, 38, 38)
                        .addComponent(currPlayerNameLabel))
                    .addGroup(TakeTurnPanelLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(TakeTurnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkForMonopBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rollDiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(TakeTurnPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(communityPotTitleLabel)
                        .addGap(18, 18, 18)
                        .addComponent(communityPotAmtLabel)))
                .addGap(65, 65, 65))
        );
        TakeTurnPanelLayout.setVerticalGroup(
            TakeTurnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TakeTurnPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TakeTurnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currTurnLabel)
                    .addComponent(currPlayerNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rollDiceButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkForMonopBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EndGameButton)
                .addGap(18, 18, 18)
                .addGroup(TakeTurnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(communityPotTitleLabel)
                    .addComponent(communityPotAmtLabel))
                .addGap(28, 28, 28))
        );

        p1StatsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p1StatsPanel.setPreferredSize(new java.awt.Dimension(250, 300));

        p1JailStatusLbl.setText("Jail Status:");

        p1StatsTitleLbl.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        p1StatsTitleLbl.setForeground(new java.awt.Color(254, 1, 1));
        p1StatsTitleLbl.setText("Player 1:");

        p1BankAccountLbl.setText("Bank Account:      $");

        p1BalanceLbl.setText("1500");

        p1PropertiesLbl.setText("Properties Owned:");

        p1IsInJailLbl.setText("Not In Jail");

        p1CurrentSpaceLbl.setText("Current Space:");

        p1LocationLbl.setText("Go");

        P1PropOwnedArea.setEditable(false);
        P1PropOwnedArea.setColumns(20);
        P1PropOwnedArea.setRows(5);
        P1ScrollPane.setViewportView(P1PropOwnedArea);

        javax.swing.GroupLayout p1StatsPanelLayout = new javax.swing.GroupLayout(p1StatsPanel);
        p1StatsPanel.setLayout(p1StatsPanelLayout);
        p1StatsPanelLayout.setHorizontalGroup(
            p1StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1StatsPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(p1StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p1StatsPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(p1StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1LocationLbl)
                            .addComponent(p1IsInJailLbl)))
                    .addComponent(P1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(p1StatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1StatsTitleLbl)
                    .addGroup(p1StatsPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(p1StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p1JailStatusLbl)
                            .addGroup(p1StatsPanelLayout.createSequentialGroup()
                                .addComponent(p1BankAccountLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p1BalanceLbl))
                            .addComponent(p1CurrentSpaceLbl)
                            .addComponent(p1PropertiesLbl))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p1StatsPanelLayout.setVerticalGroup(
            p1StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1StatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p1StatsTitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1BankAccountLbl)
                    .addComponent(p1BalanceLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p1JailStatusLbl)
                    .addComponent(p1IsInJailLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p1StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p1LocationLbl)
                    .addComponent(p1CurrentSpaceLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p1PropertiesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P1ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p2StatsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p2StatsPanel.setPreferredSize(new java.awt.Dimension(250, 300));

        p2JailStatusLbl.setText("Jail Status:");

        p2StatsTitleLbl.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        p2StatsTitleLbl.setForeground(new java.awt.Color(0, 212, 255));
        p2StatsTitleLbl.setText("Player 2:");

        p2BankAccountLbl.setText("Bank Account:      $");

        p2BalanceLbl.setText("1500");

        p2PropertiesLbl.setText("Properties Owned:");

        p2IsInJailLbl.setText("Not In Jail");

        p2CurrentSpaceLbl.setText("Current Space:");

        p2LocationLbl.setText("Go");

        P2PropOwnedArea.setEditable(false);
        P2PropOwnedArea.setColumns(20);
        P2PropOwnedArea.setRows(5);
        P2ScrollPane.setViewportView(P2PropOwnedArea);

        javax.swing.GroupLayout p2StatsPanelLayout = new javax.swing.GroupLayout(p2StatsPanel);
        p2StatsPanel.setLayout(p2StatsPanelLayout);
        p2StatsPanelLayout.setHorizontalGroup(
            p2StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2StatsPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(p2StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2StatsPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(p2StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2LocationLbl)
                            .addComponent(p2IsInJailLbl)))
                    .addComponent(P2ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(p2StatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2StatsTitleLbl)
                    .addGroup(p2StatsPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(p2StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p2JailStatusLbl)
                            .addGroup(p2StatsPanelLayout.createSequentialGroup()
                                .addComponent(p2BankAccountLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p2BalanceLbl))
                            .addComponent(p2CurrentSpaceLbl)
                            .addComponent(p2PropertiesLbl))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p2StatsPanelLayout.setVerticalGroup(
            p2StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2StatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p2StatsTitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p2StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2BankAccountLbl)
                    .addComponent(p2BalanceLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p2StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p2JailStatusLbl)
                    .addComponent(p2IsInJailLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p2StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p2LocationLbl)
                    .addComponent(p2CurrentSpaceLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p2PropertiesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P2ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p3StatsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p3StatsPanel.setPreferredSize(new java.awt.Dimension(250, 300));

        p3JailStatusLbl.setText("Jail Status:");

        p3StatsTitleLbl.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        p3StatsTitleLbl.setForeground(new java.awt.Color(60, 218, 6));
        p3StatsTitleLbl.setText("Player 3:");

        p3BankAccountLbl.setText("Bank Account:      $");

        p3BalanceLbl.setText("1500");

        p3PropertiesLbl.setText("Properties Owned:");

        p3IsInJailLbl.setText("Not In Jail");

        p3CurrentSpaceLbl.setText("Current Space:");

        p3LocationLbl.setText("Go");

        P3PropOwnedArea.setEditable(false);
        P3PropOwnedArea.setColumns(20);
        P3PropOwnedArea.setRows(5);
        P3ScrollPane.setViewportView(P3PropOwnedArea);

        javax.swing.GroupLayout p3StatsPanelLayout = new javax.swing.GroupLayout(p3StatsPanel);
        p3StatsPanel.setLayout(p3StatsPanelLayout);
        p3StatsPanelLayout.setHorizontalGroup(
            p3StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3StatsPanelLayout.createSequentialGroup()
                .addGroup(p3StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3StatsPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(P3ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p3StatsPanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(p3StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p3StatsPanelLayout.createSequentialGroup()
                                .addGroup(p3StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(p3CurrentSpaceLbl)
                                    .addComponent(p3JailStatusLbl))
                                .addGroup(p3StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p3StatsPanelLayout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(p3IsInJailLbl))
                                    .addGroup(p3StatsPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(p3LocationLbl))))
                            .addGroup(p3StatsPanelLayout.createSequentialGroup()
                                .addComponent(p3BankAccountLbl)
                                .addGap(18, 18, 18)
                                .addComponent(p3BalanceLbl))
                            .addComponent(p3PropertiesLbl))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(p3StatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p3StatsTitleLbl)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p3StatsPanelLayout.setVerticalGroup(
            p3StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3StatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p3StatsTitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p3StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p3BalanceLbl)
                    .addComponent(p3BankAccountLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p3StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p3JailStatusLbl)
                    .addComponent(p3IsInJailLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p3StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p3CurrentSpaceLbl)
                    .addComponent(p3LocationLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p3PropertiesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P3ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        p4StatsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p4StatsPanel.setPreferredSize(new java.awt.Dimension(250, 300));

        p4JailStatusLbl.setText("Jail Status:");

        p4StatsTitleLbl.setFont(new java.awt.Font("DejaVu Sans", 1, 13)); // NOI18N
        p4StatsTitleLbl.setForeground(new java.awt.Color(255, 224, 0));
        p4StatsTitleLbl.setText("Player 4:");

        p4BankAccountLbl.setText("Bank Account:      $");

        p4BalanceLbl.setText("1500");

        p4PropertiesLbl.setText("Properties Owned:");

        p4IsInJailLbl.setText("Not In Jail");

        p4CurrentSpaceLbl.setText("Current Space:");

        p4LocationLbl.setText("Go");

        P4PropOwnedArea.setEditable(false);
        P4PropOwnedArea.setColumns(20);
        P4PropOwnedArea.setRows(5);
        P4ScrollPane.setViewportView(P4PropOwnedArea);

        javax.swing.GroupLayout p4StatsPanelLayout = new javax.swing.GroupLayout(p4StatsPanel);
        p4StatsPanel.setLayout(p4StatsPanelLayout);
        p4StatsPanelLayout.setHorizontalGroup(
            p4StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4StatsPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(p4StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4StatsPanelLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(p4StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p4LocationLbl)
                            .addComponent(p4IsInJailLbl)))
                    .addComponent(p4PropertiesLbl)
                    .addComponent(P4ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p4StatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p4StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(p4StatsTitleLbl)
                    .addGroup(p4StatsPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(p4StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(p4JailStatusLbl)
                            .addGroup(p4StatsPanelLayout.createSequentialGroup()
                                .addComponent(p4BankAccountLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(p4BalanceLbl))
                            .addComponent(p4CurrentSpaceLbl))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        p4StatsPanelLayout.setVerticalGroup(
            p4StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4StatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p4StatsTitleLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p4StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4BankAccountLbl)
                    .addComponent(p4BalanceLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p4StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4JailStatusLbl)
                    .addComponent(p4IsInJailLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p4StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(p4CurrentSpaceLbl)
                    .addComponent(p4LocationLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p4PropertiesLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(P4ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boardImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Monopoly/view/blankMonopolyBoard.jpg"))); // NOI18N
        boardImg.setText("jLabel2");
        boardImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        boardImg.setMaximumSize(new java.awt.Dimension(700, 698));
        boardImg.setMinimumSize(new java.awt.Dimension(700, 698));
        boardImg.setPreferredSize(new java.awt.Dimension(700, 700));

        messagesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        messagesPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        messagesPanel.setMinimumSize(new java.awt.Dimension(302, 434));
        messagesPanel.setLayout(new java.awt.CardLayout());

        dicePanel.setPreferredSize(new java.awt.Dimension(309, 434));

        makeMoveButton.setText("Move!");

        dice1Lbl.setText("dice1");
        dice1Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dice1Lbl.setPreferredSize(new java.awt.Dimension(100, 100));

        dice2Lbl.setText("dice2");
        dice2Lbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dice2Lbl.setPreferredSize(new java.awt.Dimension(100, 100));

        messagesLbl1.setText("--- Messages ---");

        javax.swing.GroupLayout dicePanelLayout = new javax.swing.GroupLayout(dicePanel);
        dicePanel.setLayout(dicePanelLayout);
        dicePanelLayout.setHorizontalGroup(
            dicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dicePanelLayout.createSequentialGroup()
                .addGroup(dicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dicePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(messagesLbl1))
                    .addGroup(dicePanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(dice1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dice2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dicePanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(makeMoveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        dicePanelLayout.setVerticalGroup(
            dicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dicePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messagesLbl1)
                .addGap(63, 63, 63)
                .addGroup(dicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dice1Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dice2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(makeMoveButton)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        messagesPanel.add(dicePanel, "rollRiceCard");

        propDisplayPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        propDisplayPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        propDisplayPanel.setPreferredSize(new java.awt.Dimension(309, 434));

        propPriceTitleLabel.setText("this property for:  $");

        propPriceLabel.setText("100");

        propPurchaseYesButton.setText("Yes");
        propPurchaseYesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propPurchaseYesButtonActionPerformed(evt);
            }
        });

        propPurchaseNoButton.setText("No");
        propPurchaseNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propPurchaseNoButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Would you like to purchase");

        javax.swing.GroupLayout propPanelLayout = new javax.swing.GroupLayout(propPanel);
        propPanel.setLayout(propPanelLayout);
        propPanelLayout.setHorizontalGroup(
            propPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, propPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(propPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(propPanelLayout.createSequentialGroup()
                        .addComponent(propPriceTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(propPriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addGap(33, 33, 33))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, propPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(propPurchaseYesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(propPurchaseNoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        propPanelLayout.setVerticalGroup(
            propPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(propPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propPriceTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(propPriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(propPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(propPurchaseNoButton)
                    .addComponent(propPurchaseYesButton))
                .addGap(131, 131, 131))
        );

        messagesLbl2.setText("--- Messages ---");

        propNameLabel.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        propNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propNameLabel.setText("Galloway");

        propTitleLabel.setText("You landed on:  ");

        javax.swing.GroupLayout propDisplayPanelLayout = new javax.swing.GroupLayout(propDisplayPanel);
        propDisplayPanel.setLayout(propDisplayPanelLayout);
        propDisplayPanelLayout.setHorizontalGroup(
            propDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propDisplayPanelLayout.createSequentialGroup()
                .addGroup(propDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(propDisplayPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(messagesLbl2))
                    .addGroup(propDisplayPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(propDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(propPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(propNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(propDisplayPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(propTitleLabel)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        propDisplayPanelLayout.setVerticalGroup(
            propDisplayPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propDisplayPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(messagesLbl2)
                .addGap(125, 125, 125)
                .addComponent(propTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(propNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(propPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        messagesPanel.add(propDisplayPanel, "landOnPropCard");

        genPopupPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        genPopupPanel.setPreferredSize(new java.awt.Dimension(309, 434));

        genPopupLabel.setText("                     General Message                     ");

        genPopupEndTurnButton.setText("End Turn");

        messagesLbl4.setText("--- Messages ---");

        javax.swing.GroupLayout genPopupPanelLayout = new javax.swing.GroupLayout(genPopupPanel);
        genPopupPanel.setLayout(genPopupPanelLayout);
        genPopupPanelLayout.setHorizontalGroup(
            genPopupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genPopupPanelLayout.createSequentialGroup()
                .addGroup(genPopupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(genPopupPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(genPopupLabel))
                    .addGroup(genPopupPanelLayout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(genPopupEndTurnButton))
                    .addGroup(genPopupPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(messagesLbl4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        genPopupPanelLayout.setVerticalGroup(
            genPopupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(genPopupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messagesLbl4)
                .addGap(146, 146, 146)
                .addComponent(genPopupLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(genPopupEndTurnButton)
                .addGap(83, 83, 83))
        );

        messagesPanel.add(genPopupPanel, "generalPopupCard");

        propPurchaseOutcomePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        propPurchaseOutcomePanel.setPreferredSize(new java.awt.Dimension(309, 434));

        propPurchaseOutcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        propPurchaseOutcomeLabel.setText("You have successfully purchased");

        propPurchaseEndTurnButton.setText("End Turn!");

        messagesLbl5.setText("--- Messages ---");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" this property!");

        javax.swing.GroupLayout propPurchaseOutcomePanelLayout = new javax.swing.GroupLayout(propPurchaseOutcomePanel);
        propPurchaseOutcomePanel.setLayout(propPurchaseOutcomePanelLayout);
        propPurchaseOutcomePanelLayout.setHorizontalGroup(
            propPurchaseOutcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propPurchaseOutcomePanelLayout.createSequentialGroup()
                .addGroup(propPurchaseOutcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(propPurchaseOutcomePanelLayout.createSequentialGroup()
                        .addGroup(propPurchaseOutcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(propPurchaseOutcomePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(messagesLbl5))
                            .addGroup(propPurchaseOutcomePanelLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(propPurchaseEndTurnButton)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(propPurchaseOutcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                .addContainerGap())
        );
        propPurchaseOutcomePanelLayout.setVerticalGroup(
            propPurchaseOutcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(propPurchaseOutcomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messagesLbl5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(propPurchaseOutcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(propPurchaseEndTurnButton)
                .addGap(131, 131, 131))
        );

        messagesPanel.add(propPurchaseOutcomePanel, "buyPropCard");

        monopPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        monopLabel.setText("jLabel2");

        monopYesBttn.setText("Yes");

        monopNoBttn.setText("No");
        monopNoBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monopNoBttnActionPerformed(evt);
            }
        });

        messagesLbl8.setText("--- Messages ---");

        javax.swing.GroupLayout monopPanelLayout = new javax.swing.GroupLayout(monopPanel);
        monopPanel.setLayout(monopPanelLayout);
        monopPanelLayout.setHorizontalGroup(
            monopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monopPanelLayout.createSequentialGroup()
                .addGroup(monopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monopPanelLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(monopLabel))
                    .addGroup(monopPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(monopYesBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(monopNoBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(monopPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(messagesLbl8)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        monopPanelLayout.setVerticalGroup(
            monopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messagesLbl8)
                .addGap(52, 52, 52)
                .addComponent(monopLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE)
                .addGroup(monopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monopYesBttn)
                    .addComponent(monopNoBttn))
                .addGap(150, 150, 150))
        );

        messagesPanel.add(monopPanel, "checkMonopolyCard");

        yesMonopPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        yesMonopPanel.setPreferredSize(new java.awt.Dimension(309, 434));

        yesMonopArea.setColumns(20);
        yesMonopArea.setRows(5);
        yesMonopPane.setViewportView(yesMonopArea);

        yesMonopLbl1.setText("Enter which property you would like to build");

        yesMonopLbl2.setText("Your choice: ");

        buildBttn.setText("Build!");

        messagesLbl7.setText("--- Messages ---");

        javax.swing.GroupLayout yesMonopPanelLayout = new javax.swing.GroupLayout(yesMonopPanel);
        yesMonopPanel.setLayout(yesMonopPanelLayout);
        yesMonopPanelLayout.setHorizontalGroup(
            yesMonopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yesMonopPanelLayout.createSequentialGroup()
                .addGroup(yesMonopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(yesMonopPanelLayout.createSequentialGroup()
                        .addGroup(yesMonopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(yesMonopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(yesMonopPanelLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(messagesLbl7)
                                    .addGap(125, 125, 125))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, yesMonopPanelLayout.createSequentialGroup()
                                    .addGap(76, 76, 76)
                                    .addComponent(yesMonopLbl2)
                                    .addGap(18, 18, 18)
                                    .addComponent(yesMonopField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(yesMonopPanelLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(buildBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(yesMonopPanelLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(yesMonopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, yesMonopPanelLayout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(yesMonopLbl1)))
                .addContainerGap())
        );
        yesMonopPanelLayout.setVerticalGroup(
            yesMonopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(yesMonopPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messagesLbl7)
                .addGap(38, 38, 38)
                .addComponent(yesMonopLbl1)
                .addGap(18, 18, 18)
                .addComponent(yesMonopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(yesMonopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yesMonopLbl2)
                    .addComponent(yesMonopField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(buildBttn)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        messagesPanel.add(yesMonopPanel, "yesMonopoliesCard");

        noMonopolyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        noMonopOkBttn.setText("Okay");

        noMonopLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noMonopLabel.setText("jLabel2");

        jLabel3.setText("--- Messages ---");

        javax.swing.GroupLayout noMonopolyPanelLayout = new javax.swing.GroupLayout(noMonopolyPanel);
        noMonopolyPanel.setLayout(noMonopolyPanelLayout);
        noMonopolyPanelLayout.setHorizontalGroup(
            noMonopolyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noMonopolyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noMonopolyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(noMonopolyPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 172, Short.MAX_VALUE))
                    .addComponent(noMonopLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(noMonopolyPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(noMonopOkBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        noMonopolyPanelLayout.setVerticalGroup(
            noMonopolyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noMonopolyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(117, 117, 117)
                .addComponent(noMonopLabel)
                .addGap(55, 55, 55)
                .addComponent(noMonopOkBttn)
                .addContainerGap(232, Short.MAX_VALUE))
        );

        messagesPanel.add(noMonopolyPanel, "noMonopolyCard");

        payRentPropertyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        payRentPropertyPanel.setPreferredSize(new java.awt.Dimension(309, 434));

        payRentOutcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payRentOutcomeLabel.setText("Rent outcome here");

        payRentEndTurnButton.setText("End Turn");
        payRentEndTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payRentEndTurnButtonActionPerformed(evt);
            }
        });

        payRentLocationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payRentLocationLabel.setText("Player landed on __ ");

        messagesLbl6.setText("--- Messages ---");

        javax.swing.GroupLayout payRentPropertyPanelLayout = new javax.swing.GroupLayout(payRentPropertyPanel);
        payRentPropertyPanel.setLayout(payRentPropertyPanelLayout);
        payRentPropertyPanelLayout.setHorizontalGroup(
            payRentPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payRentPropertyPanelLayout.createSequentialGroup()
                .addGroup(payRentPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(payRentLocationLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(payRentPropertyPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(payRentOutcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(payRentPropertyPanelLayout.createSequentialGroup()
                        .addGroup(payRentPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(payRentPropertyPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(messagesLbl6))
                            .addGroup(payRentPropertyPanelLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(payRentEndTurnButton)))
                        .addGap(0, 103, Short.MAX_VALUE)))
                .addContainerGap())
        );
        payRentPropertyPanelLayout.setVerticalGroup(
            payRentPropertyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payRentPropertyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messagesLbl6)
                .addGap(89, 89, 89)
                .addComponent(payRentLocationLabel)
                .addGap(29, 29, 29)
                .addComponent(payRentOutcomeLabel)
                .addGap(46, 46, 46)
                .addComponent(payRentEndTurnButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        messagesPanel.add(payRentPropertyPanel, "payRentCard");

        EndGamePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        EndGamePanel.setPreferredSize(new java.awt.Dimension(309, 434));

        endOfGameStatsLabel.setFont(new java.awt.Font("DejaVu Sans", 1, 18)); // NOI18N
        endOfGameStatsLabel.setText("END OF GAME STATS");

        firstPlaceTitleLabel.setText("The winner is:");

        firstPlaceLabel.setFont(new java.awt.Font("DejaVu Sans", 2, 18)); // NOI18N
        firstPlaceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        firstPlaceLabel.setText("jLabel2");

        quitGameButton.setText("Quit");

        messageLbl3.setText("--- Messages ---");

        javax.swing.GroupLayout EndGamePanelLayout = new javax.swing.GroupLayout(EndGamePanel);
        EndGamePanel.setLayout(EndGamePanelLayout);
        EndGamePanelLayout.setHorizontalGroup(
            EndGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EndGamePanelLayout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addGroup(EndGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(firstPlaceTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(endOfGameStatsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
            .addGroup(EndGamePanelLayout.createSequentialGroup()
                .addGroup(EndGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EndGamePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(messageLbl3))
                    .addGroup(EndGamePanelLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(quitGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EndGamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(firstPlaceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        EndGamePanelLayout.setVerticalGroup(
            EndGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EndGamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageLbl3)
                .addGap(26, 26, 26)
                .addComponent(endOfGameStatsLabel)
                .addGap(42, 42, 42)
                .addComponent(firstPlaceTitleLabel)
                .addGap(34, 34, 34)
                .addComponent(firstPlaceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(quitGameButton)
                .addGap(112, 112, 112))
        );

        messagesPanel.add(EndGamePanel, "endGameCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boardImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(messagesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(TakeTurnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(512, 512, 512)
                                .addComponent(p3StatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(p1StatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(p2StatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p4StatsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))
                .addGap(0, 4, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(boardImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TakeTurnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(messagesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(p4StatsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                        .addComponent(p3StatsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(p1StatsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                        .addComponent(p2StatsPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtP2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtP2ActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBtnActionPerformed

    private void payRentEndTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payRentEndTurnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payRentEndTurnButtonActionPerformed

    private void monopNoBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monopNoBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monopNoBttnActionPerformed

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_playBtnActionPerformed

    private void propPurchaseNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propPurchaseNoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propPurchaseNoButtonActionPerformed

    private void propPurchaseYesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propPurchaseYesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propPurchaseYesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonopolyView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonopolyView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonopolyView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonopolyView.class.getName()).log(
                    java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonopolyView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EndGameButton;
    private javax.swing.JPanel EndGamePanel;
    private javax.swing.JTextArea P1PropOwnedArea;
    private javax.swing.JScrollPane P1ScrollPane;
    private javax.swing.JTextArea P2PropOwnedArea;
    private javax.swing.JScrollPane P2ScrollPane;
    private javax.swing.JTextArea P3PropOwnedArea;
    private javax.swing.JScrollPane P3ScrollPane;
    private javax.swing.JTextArea P4PropOwnedArea;
    private javax.swing.JScrollPane P4ScrollPane;
    private javax.swing.JDialog PlayDialog;
    private javax.swing.JPanel TakeTurnPanel;
    private javax.swing.JLabel boardImg;
    private javax.swing.JButton buildBttn;
    private javax.swing.JButton checkForMonopBttn;
    private javax.swing.JLabel communityPotAmtLabel;
    private javax.swing.JLabel communityPotTitleLabel;
    private javax.swing.JLabel currPlayerNameLabel;
    private javax.swing.JLabel currTurnLabel;
    private javax.swing.JLabel dice1Lbl;
    private javax.swing.JLabel dice2Lbl;
    private javax.swing.JPanel dicePanel;
    private javax.swing.JLabel endOfGameStatsLabel;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel firstPlaceLabel;
    private javax.swing.JLabel firstPlaceTitleLabel;
    private javax.swing.JButton genPopupEndTurnButton;
    private javax.swing.JLabel genPopupLabel;
    private javax.swing.JPanel genPopupPanel;
    private javax.swing.JPanel inputPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblGreeting2;
    private javax.swing.JButton makeMoveButton;
    private javax.swing.JPanel messagesPanel;
    private javax.swing.JLabel monopLabel;
    private javax.swing.JButton monopNoBttn;
    private javax.swing.JPanel monopPanel;
    private javax.swing.JButton monopYesBttn;
    private javax.swing.JLabel noMonopLabel;
    private javax.swing.JButton noMonopOkBttn;
    private javax.swing.JPanel noMonopolyPanel;
    private javax.swing.JLabel p1BalanceLbl;
    private javax.swing.JLabel p1IsInJailLbl;
    private javax.swing.JLabel p1LocationLbl;
    private javax.swing.JPanel p1StatsPanel;
    private javax.swing.JLabel p1StatsTitleLbl;
    private javax.swing.JLabel p2BalanceLbl;
    private javax.swing.JLabel p2IsInJailLbl;
    private javax.swing.JLabel p2LocationLbl;
    private javax.swing.JPanel p2StatsPanel;
    private javax.swing.JLabel p2StatsTitleLbl;
    private javax.swing.JLabel p3BalanceLbl;
    private javax.swing.JLabel p3IsInJailLbl;
    private javax.swing.JLabel p3LocationLbl;
    private javax.swing.JPanel p3StatsPanel;
    private javax.swing.JLabel p3StatsTitleLbl;
    private javax.swing.JLabel p4BalanceLbl;
    private javax.swing.JLabel p4IsInJailLbl;
    private javax.swing.JLabel p4LocationLbl;
    private javax.swing.JPanel p4StatsPanel;
    private javax.swing.JLabel p4StatsTitleLbl;
    private javax.swing.JButton payRentEndTurnButton;
    private javax.swing.JLabel payRentLocationLabel;
    private javax.swing.JLabel payRentOutcomeLabel;
    private javax.swing.JPanel payRentPropertyPanel;
    private javax.swing.JButton playBtn;
    private javax.swing.JPanel propDisplayPanel;
    private javax.swing.JLabel propNameLabel;
    private javax.swing.JPanel propPanel;
    private javax.swing.JLabel propPriceLabel;
    private javax.swing.JLabel propPriceTitleLabel;
    private javax.swing.JButton propPurchaseEndTurnButton;
    private javax.swing.JButton propPurchaseNoButton;
    private javax.swing.JLabel propPurchaseOutcomeLabel;
    private javax.swing.JPanel propPurchaseOutcomePanel;
    private javax.swing.JButton propPurchaseYesButton;
    private javax.swing.JLabel propTitleLabel;
    private javax.swing.JButton quitGameButton;
    private javax.swing.JButton rollDiceButton;
    private javax.swing.JTextField txtP1;
    private javax.swing.JTextField txtP2;
    private javax.swing.JTextField txtP3;
    private javax.swing.JTextField txtP4;
    private javax.swing.JTextArea yesMonopArea;
    private javax.swing.JTextField yesMonopField;
    private javax.swing.JLabel yesMonopLbl1;
    private javax.swing.JLabel yesMonopLbl2;
    private javax.swing.JScrollPane yesMonopPane;
    private javax.swing.JPanel yesMonopPanel;
    // End of variables declaration//GEN-END:variables

    public JButton getEndGameButton() {
        return EndGameButton;
    }

    public JTextArea getP1PropOwnedArea() {
        return P1PropOwnedArea;
    }

    public JTextArea getP2PropOwnedArea() {
        return P2PropOwnedArea;
    }

    public JTextArea getP3PropOwnedArea() {
        return P3PropOwnedArea;
    }

    public JTextArea getP4PropOwnedArea() {
        return P4PropOwnedArea;
    }

    public JScrollPane getP1ScrollPane() {
        return P1ScrollPane;
    }

    public JScrollPane getP2ScrollPane() {
        return P2ScrollPane;
    }

    public JScrollPane getP3ScrollPane() {
        return P3ScrollPane;
    }

    public JScrollPane getP4ScrollPane() {
        return P4ScrollPane;
    }

    public JLabel getMonopLabel() {
        return monopLabel;
    }

    public JButton getMonopNoBttn() {
        return monopNoBttn;
    }

    public JPanel getMonopPanel() {
        return monopPanel;
    }

    public JButton getMonopYesBttn() {
        return monopYesBttn;
    }

    public void setP1ScrollPane(JScrollPane P1ScrollPane) {
        this.P1ScrollPane = P1ScrollPane;
    }

    public void setP2ScrollPane(JScrollPane P2ScrollPane) {
        this.P2ScrollPane = P2ScrollPane;
    }

    public void setP3ScrollPane(JScrollPane P3ScrollPane) {
        this.P3ScrollPane = P3ScrollPane;
    }

    public void setP4ScrollPane(JScrollPane P4ScrollPane) {
        this.P4ScrollPane = P4ScrollPane;
    }

    public void setPropPurchaseEndTurnButton(JButton propPurchaseEndTurnButton) {
        this.propPurchaseEndTurnButton = propPurchaseEndTurnButton;
    }

    public JButton getGenPopupEndTurnButton() {
        return genPopupEndTurnButton;
    }

    public JLabel getGenPopupLabel() {
        return genPopupLabel;
    }

    public JPanel getGenPopupPanel() {
        return genPopupPanel;
    }

    public void setGenPopupEndTurnButton(JButton genPopupEndTurnButton) {
        this.genPopupEndTurnButton = genPopupEndTurnButton;
    }

    public void setGenPopupLabel(JLabel genPopupLabel) {
        this.genPopupLabel = genPopupLabel;
    }

    public void setGenPopupPanel(JPanel genPopupPanel) {
        this.genPopupPanel = genPopupPanel;
    }

    public void setPropPurchaseOutcomeLabel(JLabel propPurchaseOutcomeLabel) {
        this.propPurchaseOutcomeLabel = propPurchaseOutcomeLabel;
    }

    public void setPropPurchaseOutcomePanel(JPanel propPurchaseOutcomePanel) {
        this.propPurchaseOutcomePanel = propPurchaseOutcomePanel;
    }

    public JButton getBuildBttn() {
        return buildBttn;
    }

    public JTextArea getYesMonopArea() {
        return yesMonopArea;
    }

    public JTextField getYesMonopField() {
        return yesMonopField;
    }

    public JLabel getYesMonopLbl1() {
        return yesMonopLbl1;
    }

    public JLabel getYesMonopLbl2() {
        return yesMonopLbl2;
    }

    public JScrollPane getYesMonopPane() {
        return yesMonopPane;
    }

    public JPanel getYesMonopPanel() {
        return yesMonopPanel;
    }

    public JButton getPropPurchaseEndTurnButton() {
        return propPurchaseEndTurnButton;
    }

    public JLabel getPropPurchaseOutcomeLabel() {
        return propPurchaseOutcomeLabel;
    }

    public JPanel getPropPurchaseOutcomePanel() {
        return propPurchaseOutcomePanel;
    }

    public JLabel getPropNameLabel() {
        return propNameLabel;
    }

    public JPanel getPropPanel() {
        return propPanel;
    }

    public JLabel getPropPriceLabel() {
        return propPriceLabel;
    }

    public JLabel getPropPriceTitleLabel() {
        return propPriceTitleLabel;
    }

    public JButton getPropPurchaseNoButton() {
        return propPurchaseNoButton;
    }

    public JButton getPropPurchaseYesButton() {
        return propPurchaseYesButton;
    }

    public JLabel getPropTitleLabel() {
        return propTitleLabel;
    }

    public void setPropNameLabel(JLabel propNameLabel) {
        this.propNameLabel = propNameLabel;
    }

    public void setPropPanel(JPanel propPanel) {
        this.propPanel = propPanel;
    }

    public void setPropPriceLabel(JLabel propPriceLabel) {
        this.propPriceLabel = propPriceLabel;
    }

    public void setPropPriceTitleLabel(JLabel propPriceTitleLabel) {
        this.propPriceTitleLabel = propPriceTitleLabel;
    }

    public void setPropPurchaseNoButton(JButton propPurchaseNoButton) {
        this.propPurchaseNoButton = propPurchaseNoButton;
    }

    public void setPropPurchaseYesButton(JButton propPurchaseYesButton) {
        this.propPurchaseYesButton = propPurchaseYesButton;
    }

    public void setPropTitleLabel(JLabel propTitleLabel) {
        this.propTitleLabel = propTitleLabel;
    }

    public JButton getPayRentEndTurnButton() {
        return payRentEndTurnButton;
    }

    public JLabel getPayRentLocationLabel() {
        return payRentLocationLabel;
    }

    public JLabel getPayRentOutcomeLabel() {
        return payRentOutcomeLabel;
    }

    public JPanel getPayRentPropertyPanel() {
        return payRentPropertyPanel;
    }

    public void setPayRentEndTurnButton(JButton payRentEndTurnButton) {
        this.payRentEndTurnButton = payRentEndTurnButton;
    }

    public void setPayRentLocationLabel(JLabel payRentLocationLabel) {
        this.payRentLocationLabel = payRentLocationLabel;
    }

    public void setPayRentOutcomeLabel(JLabel payRentOutcomeLabel) {
        this.payRentOutcomeLabel = payRentOutcomeLabel;
    }

    public void setPayRentPropertyPanel(JPanel payRentPropertyPanel) {
        this.payRentPropertyPanel = payRentPropertyPanel;
    }

    public JPanel getRollPanel() {
        return dicePanel;
    }

    public void setRollPanel(JPanel rollPanel) {
        this.dicePanel = rollPanel;
    }

    public JLabel getP1BalanceLbl() {
        return p1BalanceLbl;
    }

    public JLabel getP1IsInJailLbl() {
        return p1IsInJailLbl;
    }

    public JLabel getP1LocationLbl() {
        return p1LocationLbl;
    }

    public JPanel getP1StatsPanel() {
        return p1StatsPanel;
    }

    public JLabel getP1StatsTitleLbl() {
        return p1StatsTitleLbl;
    }

    public JLabel getP2BalanceLbl() {
        return p2BalanceLbl;
    }

    public JLabel getP2IsInJailLbl() {
        return p2IsInJailLbl;
    }

    public JLabel getP2LocationLbl() {
        return p2LocationLbl;
    }

    public JPanel getP2StatsPanel() {
        return p2StatsPanel;
    }

    public JLabel getP2StatsTitleLbl() {
        return p2StatsTitleLbl;
    }

    public JLabel getP3BalanceLbl() {
        return p3BalanceLbl;
    }

    public JLabel getP3IsInJailLbl() {
        return p3IsInJailLbl;
    }

    public JLabel getP3LocationLbl() {
        return p3LocationLbl;
    }

    public JPanel getP3StatsPanel() {
        return p3StatsPanel;
    }

    public JLabel getP3StatsTitleLbl() {
        return p3StatsTitleLbl;
    }

    public JLabel getP4BalanceLbl() {
        return p4BalanceLbl;
    }

    public JLabel getP4IsInJailLbl() {
        return p4IsInJailLbl;
    }

    public JLabel getP4LocationLbl() {
        return p4LocationLbl;
    }

    public JPanel getP4StatsPanel() {
        return p4StatsPanel;
    }

    public JLabel getP4StatsTitleLbl() {
        return p4StatsTitleLbl;
    }

    public void setP1StatsPanel(JPanel p1StatsPanel) {
        this.p1StatsPanel = p1StatsPanel;
    }

    public void setP2StatsPanel(JPanel p2StatsPanel) {
        this.p2StatsPanel = p2StatsPanel;
    }

    public void setP3StatsPanel(JPanel p3StatsPanel) {
        this.p3StatsPanel = p3StatsPanel;
    }

    public void setP4StatsPanel(JPanel p4StatsPanel) {
        this.p4StatsPanel = p4StatsPanel;
    }

    public JDialog getPlayDialog() {
        return PlayDialog;
    }

    public JButton getExitBtn() {
        return exitBtn;
    }

    public JButton getPlayBtn() {
        return playBtn;
    }

    public JTextField getTxtP1() {
        return txtP1;
    }

    public JTextField getTxtP2() {
        return txtP2;
    }

    public JTextField getTxtP3() {
        return txtP3;
    }

    public JTextField getTxtP4() {
        return txtP4;
    }

    public JPanel getInputPanel() {
        return inputPanel;
    }

    public JLabel getLblGreeting2() {
        return lblGreeting2;
    }

    public void setPlayDialog(JDialog PlayDialog) {
        this.PlayDialog = PlayDialog;
    }

    public void setExitBtn(JButton exitBtn) {
        this.exitBtn = exitBtn;
    }

    public void setInputPanel(JPanel inputPanel) {
        this.inputPanel = inputPanel;
    }

    public void setLblGreeting2(JLabel lblGreeting2) {
        this.lblGreeting2 = lblGreeting2;
    }

    public void setPlayBtn(JButton playBtn) {
        this.playBtn = playBtn;
    }

    public void setTxtP1(JTextField txtP1) {
        this.txtP1 = txtP1;
    }

    public void setTxtP2(JTextField txtP2) {
        this.txtP2 = txtP2;
    }

    public void setTxtP3(JTextField txtP3) {
        this.txtP1 = txtP3;
    }

    public void setTxtP4(JTextField txtP4) {
        this.txtP2 = txtP4;
    }

    public JButton getMakeMoveButton() {
        return makeMoveButton;
    }

    public void setMakeMoveButton(JButton makeMoveButton) {
        this.makeMoveButton = makeMoveButton;
    }

    public void setPlayer1StatsPanel(JPanel Player1StatsPanel) {
        this.p1StatsPanel = Player1StatsPanel;
    }

    public void setTakeTurnPanel(JPanel TakeTurnPanel) {
        this.TakeTurnPanel = TakeTurnPanel;
    }

    public void setCheckForMonopBttn(JButton checkForMonopBttn) {
        this.checkForMonopBttn = checkForMonopBttn;
    }

    public void setCommunityPotAmtLabel(JLabel communityPotAmtLabel) {
        this.communityPotAmtLabel = communityPotAmtLabel;
    }

    public void setCommunityPotTitleLabel(JLabel communityPotTitleLabel) {
        this.communityPotTitleLabel = communityPotTitleLabel;
    }

    public void setCurrPlayerNameLabel(JLabel currPlayerNameLabel) {
        this.currPlayerNameLabel = currPlayerNameLabel;
    }

    public void setCurrTurnLabel(JLabel currTurnLabel) {
        this.currTurnLabel = currTurnLabel;
    }

    public void setRollDiceButton(JButton rollDiceButton) {
        this.rollDiceButton = rollDiceButton;
    }

    public JPanel getPlayer1StatsPanel() {
        return p1StatsPanel;
    }

    public JPanel getTakeTurnPanel() {
        return TakeTurnPanel;
    }

    public JButton getCheckForMonopBttn() {
        return checkForMonopBttn;
    }

    public JLabel getCommunityPotAmtLabel() {
        return communityPotAmtLabel;
    }

    public JLabel getCommunityPotTitleLabel() {
        return communityPotTitleLabel;
    }

    public JLabel getCurrPlayerNameLabel() {
        return currPlayerNameLabel;
    }

    public JLabel getCurrTurnLabel() {
        return currTurnLabel;
    }

    public JButton getRollDiceButton() {
        return rollDiceButton;
    }

    public void setP1BalanceLbl(JLabel p1BalanceLbl) {
        this.p1BalanceLbl = p1BalanceLbl;
    }

    public void setP1IsInJailLbl(JLabel p1IsInJailLbl) {
        this.p1IsInJailLbl = p1IsInJailLbl;
    }

    public void setP1LocationLbl(JLabel p1LocationLbl) {
        this.p1LocationLbl = p1LocationLbl;
    }

    public void setP1StatsTitleLbl(JLabel p1StatsTitleLbl) {
        this.p1StatsTitleLbl = p1StatsTitleLbl;
    }

    public void setP2BalanceLbl(JLabel p2BalanceLbl) {
        this.p2BalanceLbl = p2BalanceLbl;
    }

    public void setP2IsInJailLbl(JLabel p2IsInJailLbl) {
        this.p2IsInJailLbl = p2IsInJailLbl;
    }

    public void setP2LocationLbl(JLabel p2LocationLbl) {
        this.p2LocationLbl = p2LocationLbl;
    }

    public void setP2StatsTitleLbl(JLabel p2StatsTitleLbl) {
        this.p2StatsTitleLbl = p2StatsTitleLbl;
    }

    public void setP3BalanceLbl(JLabel p3BalanceLbl) {
        this.p3BalanceLbl = p3BalanceLbl;
    }

    public void setP3IsInJailLbl(JLabel p3IsInJailLbl) {
        this.p3IsInJailLbl = p3IsInJailLbl;
    }

    public void setP3LocationLbl(JLabel p3LocationLbl) {
        this.p3LocationLbl = p3LocationLbl;
    }

    public void setP3StatsTitleLbl(JLabel p3StatsTitleLbl) {
        this.p3StatsTitleLbl = p3StatsTitleLbl;
    }

    public void setP4BalanceLbl(JLabel p4BalanceLbl) {
        this.p4BalanceLbl = p4BalanceLbl;
    }

    public void setP4IsInJailLbl(JLabel p4IsInJailLbl) {
        this.p4IsInJailLbl = p4IsInJailLbl;
    }

    public void setP4LocationLbl(JLabel p4LocationLbl) {
        this.p4LocationLbl = p4LocationLbl;
    }

    public void setP4StatsTitleLbl(JLabel p4StatsTitleLbl) {
        this.p4StatsTitleLbl = p4StatsTitleLbl;
    }

    public JPanel getEndGamePanel() {
        return EndGamePanel;
    }

    public JLabel getEndOfGameStatsLabel() {
        return endOfGameStatsLabel;
    }

    public JLabel getFirstPlaceLabel() {
        return firstPlaceLabel;
    }

    public JLabel getFirstPlaceTitleLabel() {
        return firstPlaceTitleLabel;
    }

    public JButton getQuitGameButton() {
        return quitGameButton;
    }

    public JLabel getNoMonopLabel() {
        return noMonopLabel;
    }

    public JButton getNoMonopOkBttn() {
        return noMonopOkBttn;
    }

    public JLabel getBoardImg() {
        return boardImg;
    }

    public void setBoardImg(JLabel boardImg) {
        this.boardImg = boardImg;
    }

    public JLabel getDice1Lbl() {
        return dice1Lbl;
    }

    public void setDice1Lbl(JLabel dice1Lbl) {
        this.dice1Lbl = dice1Lbl;
    }

    public JLabel getDice2Lbl() {
        return dice2Lbl;
    }

    public void setDice2Lbl(JLabel dice2Lbl) {
        this.dice2Lbl = dice2Lbl;
    }

    public JPanel getDicePanel() {
        return dicePanel;
    }

    public JPanel getPropDisplayPanel() {
        return propDisplayPanel;
    }

    public JPanel getMessagesPanel() {
        return messagesPanel;
    }

    // Wont let me set getter for getEndGamePanel !
}
